CREATE TABLE torneos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    deporte VARCHAR(60) NOT NULL,
    categoria VARCHAR(60) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_torneo_nombre UNIQUE (nombre)
);

CREATE TABLE equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    torneo_id BIGINT NOT NULL,
    CONSTRAINT fk_equipo_torneo
        FOREIGN KEY (torneo_id) REFERENCES torneos(id),
    CONSTRAINT uk_equipo_torneo_nombre UNIQUE (torneo_id, nombre)
);

CREATE TABLE jugadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    equipo_id BIGINT NOT NULL,
    CONSTRAINT fk_jugador_equipo
        FOREIGN KEY (equipo_id) REFERENCES equipos(id) ON DELETE CASCADE,
    CONSTRAINT uk_jugador_equipo_nombre UNIQUE (equipo_id, nombre)
);

CREATE TABLE partidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    cancha VARCHAR(120) NOT NULL,
    torneo_id BIGINT NOT NULL,
    equipo_local_id BIGINT NOT NULL,
    equipo_visitante_id BIGINT NOT NULL,
    CONSTRAINT fk_partido_torneo
        FOREIGN KEY (torneo_id) REFERENCES torneos(id),
    CONSTRAINT fk_partido_equipo_local
        FOREIGN KEY (equipo_local_id) REFERENCES equipos(id),
    CONSTRAINT fk_partido_equipo_visitante
        FOREIGN KEY (equipo_visitante_id) REFERENCES equipos(id),
    CONSTRAINT ck_partido_equipos_diferentes
        CHECK (equipo_local_id <> equipo_visitante_id)
);

CREATE INDEX idx_equipos_torneo ON equipos(torneo_id);
CREATE INDEX idx_jugadores_equipo ON jugadores(equipo_id);
CREATE INDEX idx_partidos_torneo_fecha_hora ON partidos(torneo_id, fecha, hora);
